"""reinit migration 

Revision ID: 0eeaf9511c74
Revises: 
Create Date: 2026-10-05 13:57:37.573210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eeaf9511c74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('titre', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_deleted_at'), 'feedback', ['deleted_at'], unique=False)
    op.alter_column('documents', 'download_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'save_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'vue_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('documents_classe_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'classe', ['classe_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_classe_id_fkey'), 'documents', 'classe', ['classe_id'], ['id'])
    op.alter_column('documents', 'vue_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'save_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'download_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_feedback_deleted_at'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
