"""add thumbnails 

Revision ID: 163ead66f9f5
Revises: 21f8c3afd0a8
Create Date: 2026-09-22 09:46:28.890637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163ead66f9f5'
down_revision: Union[str, Sequence[str], None] = '21f8c3afd0a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('thumbnail_url', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'thumbnail_url')
    # ### end Alembic commands ###
