"""add counter 

Revision ID: 21f8c3afd0a8
Revises: 9cd6f60c7ce2
Create Date: 2026-09-22 07:35:41.818394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f8c3afd0a8'
down_revision: Union[str, Sequence[str], None] = '9cd6f60c7ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('download_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('save_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('vue_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'vue_count')
    op.drop_column('documents', 'save_count')
    op.drop_column('documents', 'download_count')
    # ### end Alembic commands ###
