"""rename description

Revision ID: 29650cb429bf
Revises: 21cded45f087
Create Date: 2026-09-15 19:02:24.841381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29650cb429bf'
down_revision: Union[str, Sequence[str], None] = '21cded45f087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('description', sa.String(length=200), nullable=True))
    op.drop_index(op.f('ix_folders_desciption'), table_name='folders')
    op.create_index(op.f('ix_folders_description'), 'folders', ['description'], unique=False)
    op.drop_column('folders', 'desciption')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('desciption', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_folders_description'), table_name='folders')
    op.create_index(op.f('ix_folders_desciption'), 'folders', ['desciption'], unique=False)
    op.drop_column('folders', 'description')
    # ### end Alembic commands ###
