"""Add annonces 

Revision ID: 43c60956c50d
Revises: 69acc517bde2
Create Date: 2026-08-06 12:28:47.321814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43c60956c50d'
down_revision: Union[str, Sequence[str], None] = '69acc517bde2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annonces',
    sa.Column('titre', sa.String(length=150), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('important', sa.Boolean(), nullable=False),
    sa.Column('statut', sa.Enum('active', 'archivee', name='annoncestatut'), nullable=False),
    sa.Column('auteur_id', sa.Uuid(), nullable=False),
    sa.Column('classe_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auteur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['classe_id'], ['classe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annonces_classe_id'), 'annonces', ['classe_id'], unique=False)
    op.create_table('annonce_lectures',
    sa.Column('annonce_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['annonce_id'], ['annonces.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annonce_id', 'user_id', name='uq_annonce_user_lecture')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annonce_lectures')
    op.drop_index(op.f('ix_annonces_classe_id'), table_name='annonces')
    op.drop_table('annonces')
    # ### end Alembic commands ###
