"""improve relation

Revision ID: 686977195b72
Revises: 89eab1969d0b
Create Date: 2026-09-10 19:38:30.823813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '686977195b72'
down_revision: Union[str, Sequence[str], None] = '89eab1969d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classe_moderateurs_classe_id'), table_name='classe_moderateurs')
    op.drop_index(op.f('ix_classe_moderateurs_deleted_at'), table_name='classe_moderateurs')
    op.drop_table('classe_moderateurs')
    op.add_column('annonce_lectures', sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('annonce_lectures', sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_annonce_lectures_deleted_at'), table_name='annonce_lectures')
    op.drop_column('annonce_lectures', 'updated_at')
    op.drop_column('annonce_lectures', 'deleted_at')
    op.drop_column('annonce_lectures', 'created_at')
    op.add_column('annonces', sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('annonces', sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_annonces_deleted_at'), table_name='annonces')
    op.drop_column('annonces', 'deleted_at')
    op.drop_column('annonces', 'updated_at')
    op.drop_column('annonces', 'created_at')
    op.add_column('classe', sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('classe', sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_classe_deleted_at'), table_name='classe')
    op.drop_column('classe', 'deleted_at')
    op.drop_column('classe', 'updated_at')
    op.drop_column('classe', 'created_at')
    op.add_column('document_sauvegardes', sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('document_sauvegardes', sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_document_sauvegardes_deleted_at'), table_name='document_sauvegardes')
    op.create_index(op.f('ix_document_sauvegardes_document_id'), 'document_sauvegardes', ['document_id'], unique=False)
    op.drop_column('document_sauvegardes', 'updated_at')
    op.drop_column('document_sauvegardes', 'deleted_at')
    op.drop_column('document_sauvegardes', 'created_at')
    op.add_column('documents', sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('documents', sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents')
    op.create_index(op.f('ix_documents_validated_by_id'), 'documents', ['validated_by_id'], unique=False)
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'deleted_at')
    op.drop_column('documents', 'created_at')
    op.add_column('subject', sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('subject', sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_subject_deleted_at'), table_name='subject')
    op.drop_column('subject', 'deleted_at')
    op.drop_column('subject', 'updated_at')
    op.drop_column('subject', 'created_at')
    op.add_column('users', sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_matricule'), table_name='users')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'matricule')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'deleted_at')
    op.add_column('year_univ', sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('year_univ', sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_year_univ_deleted_at'), table_name='year_univ')
    op.drop_column('year_univ', 'deleted_at')
    op.drop_column('year_univ', 'updated_at')
    op.drop_column('year_univ', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('year_univ', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('year_univ', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('year_univ', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_year_univ_deleted_at'), 'year_univ', ['deleted_at'], unique=False)
    op.drop_column('year_univ', 'update_at')
    op.drop_column('year_univ', 'create_at')
    op.add_column('users', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('matricule', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('avatar_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_matricule'), 'users', ['matricule'], unique=True)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_column('users', 'update_at')
    op.drop_column('users', 'create_at')
    op.add_column('subject', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('subject', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('subject', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_subject_deleted_at'), 'subject', ['deleted_at'], unique=False)
    op.drop_column('subject', 'update_at')
    op.drop_column('subject', 'create_at')
    op.add_column('documents', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_documents_validated_by_id'), table_name='documents')
    op.create_index(op.f('ix_documents_deleted_at'), 'documents', ['deleted_at'], unique=False)
    op.drop_column('documents', 'update_at')
    op.drop_column('documents', 'create_at')
    op.add_column('document_sauvegardes', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('document_sauvegardes', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('document_sauvegardes', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_document_sauvegardes_document_id'), table_name='document_sauvegardes')
    op.create_index(op.f('ix_document_sauvegardes_deleted_at'), 'document_sauvegardes', ['deleted_at'], unique=False)
    op.drop_column('document_sauvegardes', 'update_at')
    op.drop_column('document_sauvegardes', 'create_at')
    op.add_column('classe', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('classe', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('classe', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_classe_deleted_at'), 'classe', ['deleted_at'], unique=False)
    op.drop_column('classe', 'update_at')
    op.drop_column('classe', 'create_at')
    op.add_column('annonces', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('annonces', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('annonces', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_annonces_deleted_at'), 'annonces', ['deleted_at'], unique=False)
    op.drop_column('annonces', 'update_at')
    op.drop_column('annonces', 'create_at')
    op.add_column('annonce_lectures', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('annonce_lectures', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('annonce_lectures', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_annonce_lectures_deleted_at'), 'annonce_lectures', ['deleted_at'], unique=False)
    op.drop_column('annonce_lectures', 'update_at')
    op.drop_column('annonce_lectures', 'create_at')
    op.create_table('classe_moderateurs',
    sa.Column('classe_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classe.id'], name=op.f('classe_moderateurs_classe_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('classe_moderateurs_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('classe_moderateurs_pkey')),
    sa.UniqueConstraint('classe_id', 'user_id', name=op.f('uq_classe_user_moderateur'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', name=op.f('classe_moderateurs_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_classe_moderateurs_deleted_at'), 'classe_moderateurs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_classe_moderateurs_classe_id'), 'classe_moderateurs', ['classe_id'], unique=False)
    # ### end Alembic commands ###
