"""Impove relation

Revision ID: 69acc517bde2
Revises: ecfbd6c8166b
Create Date: 2026-08-05 21:55:08.866986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69acc517bde2'
down_revision: Union[str, Sequence[str], None] = 'ecfbd6c8166b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subject', 'coefficient',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('subject_name_key'), 'subject', type_='unique')
    op.create_unique_constraint('uq_classe_subject_name', 'subject', ['classe_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_classe_subject_name', 'subject', type_='unique')
    op.create_unique_constraint(op.f('subject_name_key'), 'subject', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('subject', 'coefficient',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
