"""améliorer notification model

Revision ID: 9cd6f60c7ce2
Revises: e11129a3a09b
Create Date: 2026-09-19 16:42:03.031414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd6f60c7ce2'
down_revision: Union[str, Sequence[str], None] = 'e11129a3a09b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('classe_id', sa.Uuid(), nullable=True))
    op.alter_column('notifications', 'to_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('notifications_to_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'classe', ['classe_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'notifications', 'users', ['to_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_to_user_id_fkey'), 'notifications', 'users', ['to_user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('notifications', 'to_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('notifications', 'classe_id')
    # ### end Alembic commands ###
