"""Change migration

Revision ID: a2b9380e12fa
Revises: b5849659efd6
Create Date: 2026-08-04 22:35:52.332251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b9380e12fa'
down_revision: Union[str, Sequence[str], None] = 'b5849659efd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classe', sa.Column('code_invitation', sa.String(length=10), nullable=False))
    op.create_index(op.f('ix_classe_code_invitation'), 'classe', ['code_invitation'], unique=True)
    op.alter_column('users', 'classe_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'classe_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_classe_code_invitation'), table_name='classe')
    op.drop_column('classe', 'code_invitation')
    # ### end Alembic commands ###
