"""reinit sqlalchemy

Revision ID: af5798059ed1
Revises: 
Create Date: 2026-09-10 21:15:02.859517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af5798059ed1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('year_univ',
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_year_univ_deleted_at'), 'year_univ', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_year_univ_is_active'), 'year_univ', ['is_active'], unique=False)
    op.create_table('classe',
    sa.Column('mention', sa.Enum('DAII', 'ICM', 'AES', 'AUTRE', name='mention'), nullable=False),
    sa.Column('niveau', sa.Enum('L1', 'L2', 'L3', 'M1', 'M2', 'AUTRE', name='niveau'), nullable=False),
    sa.Column('code_invitation', sa.String(length=10), nullable=False),
    sa.Column('year_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['year_id'], ['year_univ.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classe_code_invitation'), 'classe', ['code_invitation'], unique=True)
    op.create_index(op.f('ix_classe_deleted_at'), 'classe', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_classe_year_id'), 'classe', ['year_id'], unique=False)
    op.create_table('subject',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coefficient', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=50), nullable=False),
    sa.Column('classe_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classe_id', 'name', name='uq_classe_subject_name')
    )
    op.create_index(op.f('ix_subject_classe_id'), 'subject', ['classe_id'], unique=False)
    op.create_index(op.f('ix_subject_deleted_at'), 'subject', ['deleted_at'], unique=False)
    op.create_table('users',
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('matricule', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'moderator', 'admin', name='userrole'), nullable=False),
    sa.Column('classe_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classe.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_classe_id'), 'users', ['classe_id'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_matricule'), 'users', ['matricule'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('annonces',
    sa.Column('titre', sa.String(length=150), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('important', sa.Boolean(), nullable=False),
    sa.Column('statut', sa.Enum('active', 'archivee', name='annoncestatut'), nullable=False),
    sa.Column('date_archivage', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auteur_id', sa.Uuid(), nullable=False),
    sa.Column('classe_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['auteur_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['classe_id'], ['classe.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annonces_classe_id'), 'annonces', ['classe_id'], unique=False)
    op.create_index(op.f('ix_annonces_deleted_at'), 'annonces', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_annonces_statut'), 'annonces', ['statut'], unique=False)
    op.create_table('classe_moderateurs',
    sa.Column('classe_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classe.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classe_id', 'user_id', name='uq_classe_user_moderateur'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_classe_moderateurs_classe_id'), 'classe_moderateurs', ['classe_id'], unique=False)
    op.create_index(op.f('ix_classe_moderateurs_deleted_at'), 'classe_moderateurs', ['deleted_at'], unique=False)
    op.create_table('documents',
    sa.Column('titre', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_limite', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type_document', sa.Enum('cours', 'td', 'examen', 'corrige', 'autre', name='documenttype'), nullable=False),
    sa.Column('statut', sa.Enum('prive', 'en_attente', 'public', 'rejete', name='documentstatus'), nullable=False),
    sa.Column('motif_rejet', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('taille_octets', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('matiere_id', sa.Uuid(), nullable=True),
    sa.Column('classe_id', sa.Uuid(), nullable=False),
    sa.Column('validated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classe.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['subject.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_deleted_at'), 'documents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_documents_matiere_id'), 'documents', ['matiere_id'], unique=False)
    op.create_index('ix_documents_matiere_statut', 'documents', ['matiere_id', 'statut'], unique=False)
    op.create_index(op.f('ix_documents_owner_id'), 'documents', ['owner_id'], unique=False)
    op.create_index(op.f('ix_documents_statut'), 'documents', ['statut'], unique=False)
    op.create_table('refresh_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_sessions_jti'), 'refresh_sessions', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False)
    op.create_table('annonce_lectures',
    sa.Column('annonce_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['annonce_id'], ['annonces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annonce_id', 'user_id', name='uq_annonce_user_lecture')
    )
    op.create_index(op.f('ix_annonce_lectures_deleted_at'), 'annonce_lectures', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_annonce_lectures_user_id'), 'annonce_lectures', ['user_id'], unique=False)
    op.create_table('document_sauvegardes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'document_id', name='uq_user_document')
    )
    op.create_index(op.f('ix_document_sauvegardes_deleted_at'), 'document_sauvegardes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_document_sauvegardes_user_id'), 'document_sauvegardes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_sauvegardes_user_id'), table_name='document_sauvegardes')
    op.drop_index(op.f('ix_document_sauvegardes_deleted_at'), table_name='document_sauvegardes')
    op.drop_table('document_sauvegardes')
    op.drop_index(op.f('ix_annonce_lectures_user_id'), table_name='annonce_lectures')
    op.drop_index(op.f('ix_annonce_lectures_deleted_at'), table_name='annonce_lectures')
    op.drop_table('annonce_lectures')
    op.drop_index(op.f('ix_refresh_sessions_user_id'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_jti'), table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_index(op.f('ix_documents_statut'), table_name='documents')
    op.drop_index(op.f('ix_documents_owner_id'), table_name='documents')
    op.drop_index('ix_documents_matiere_statut', table_name='documents')
    op.drop_index(op.f('ix_documents_matiere_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_classe_moderateurs_deleted_at'), table_name='classe_moderateurs')
    op.drop_index(op.f('ix_classe_moderateurs_classe_id'), table_name='classe_moderateurs')
    op.drop_table('classe_moderateurs')
    op.drop_index(op.f('ix_annonces_statut'), table_name='annonces')
    op.drop_index(op.f('ix_annonces_deleted_at'), table_name='annonces')
    op.drop_index(op.f('ix_annonces_classe_id'), table_name='annonces')
    op.drop_table('annonces')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_matricule'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_classe_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subject_deleted_at'), table_name='subject')
    op.drop_index(op.f('ix_subject_classe_id'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_classe_year_id'), table_name='classe')
    op.drop_index(op.f('ix_classe_deleted_at'), table_name='classe')
    op.drop_index(op.f('ix_classe_code_invitation'), table_name='classe')
    op.drop_table('classe')
    op.drop_index(op.f('ix_year_univ_is_active'), table_name='year_univ')
    op.drop_index(op.f('ix_year_univ_deleted_at'), table_name='year_univ')
    op.drop_table('year_univ')
    # ### end Alembic commands ###
