"""add folder

Revision ID: af72c0abcfd5
Revises: af5798059ed1
Create Date: 2026-09-11 06:41:27.982351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af72c0abcfd5'
down_revision: Union[str, Sequence[str], None] = 'af5798059ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('desciption', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_deleted_at'), 'folders', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_folders_desciption'), 'folders', ['desciption'], unique=False)
    op.create_index(op.f('ix_folders_name'), 'folders', ['name'], unique=False)
    op.create_index(op.f('ix_folders_parent_id'), 'folders', ['parent_id'], unique=False)
    op.create_index(op.f('ix_folders_user_id'), 'folders', ['user_id'], unique=False)
    op.add_column('document_sauvegardes', sa.Column('folder_id', sa.Uuid(), nullable=True))
    op.add_column('document_sauvegardes', sa.Column('is_favorite', sa.Boolean(), nullable=False))
    op.add_column('document_sauvegardes', sa.Column('is_hidden', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'document_sauvegardes', 'folders', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_sauvegardes', type_='foreignkey')
    op.drop_column('document_sauvegardes', 'is_hidden')
    op.drop_column('document_sauvegardes', 'is_favorite')
    op.drop_column('document_sauvegardes', 'folder_id')
    op.drop_index(op.f('ix_folders_user_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_parent_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_name'), table_name='folders')
    op.drop_index(op.f('ix_folders_desciption'), table_name='folders')
    op.drop_index(op.f('ix_folders_deleted_at'), table_name='folders')
    op.drop_table('folders')
    # ### end Alembic commands ###
