"""add document

Revision ID: b3f84eb9e468
Revises: a2b9380e12fa
Create Date: 2026-08-04 23:43:24.540059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f84eb9e468'
down_revision: Union[str, Sequence[str], None] = 'a2b9380e12fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('titre', sa.String(length=150), nullable=False),
    sa.Column('type_document', sa.Enum('cours', 'td', 'examen', 'corrige', 'autre', name='documenttype'), nullable=False),
    sa.Column('statut', sa.Enum('prive', 'en_attente', 'public', 'rejete', name='documentstatus'), nullable=False),
    sa.Column('fichier_path', sa.String(length=150), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('taille_octets', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('matiere_id', sa.Uuid(), nullable=False),
    sa.Column('validated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['matiere_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['validated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
