"""Add relation

Revision ID: b5849659efd6
Revises: 27c74c2d63e9
Create Date: 2026-08-04 18:15:44.653199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5849659efd6'
down_revision: Union[str, Sequence[str], None] = '27c74c2d63e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('classe_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_users_classe_id'), 'users', ['classe_id'], unique=False)
    op.create_foreign_key(None, 'users', 'classe', ['classe_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_classe_id'), table_name='users')
    op.drop_column('users', 'classe_id')
    # ### end Alembic commands ###
