"""improve 

Revision ID: c725a1e1b3e5
Revises: af72c0abcfd5
Create Date: 2026-09-11 15:55:20.738008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c725a1e1b3e5'
down_revision: Union[str, Sequence[str], None] = 'af72c0abcfd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'classe_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'classe_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
