"""Add matricule

Revision ID: e3204ed59910
Revises: 43c60956c50d
Create Date: 2026-08-08 07:49:45.047727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3204ed59910'
down_revision: Union[str, Sequence[str], None] = '43c60956c50d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('matricule', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'users', ['matricule'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'matricule')
    # ### end Alembic commands ###
