"""Add save table

Revision ID: ecfbd6c8166b
Revises: b3f84eb9e468
Create Date: 2026-08-05 07:20:39.958491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecfbd6c8166b'
down_revision: Union[str, Sequence[str], None] = 'b3f84eb9e468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('date_limite', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'date_limite')
    op.drop_column('documents', 'description')
    # ### end Alembic commands ###
